results_dir = "/Results/AFLSMART/10HR"
fuzzer_command="/aflsmart/afl-fuzz -t TIMEOUT -m none -h -H 5 -i SEEDDIR -o OUTDIR -w peach -g /target/pkcs_template.xml -- HARNESSPATH @@ PORT"
fuzzer_fuzztime=36000# seconds
fuzzer_harness_timeout=7000
rng_seedlist=[1,3,5,7,9] # optional, list of seeds to be used with rng, if used then in the fuzzer command, specify the position using RNG special string
