results_dir = "/Results/PEACH/10HR"
fuzzer_fuzztime=36000# seconds
fuzzer_harness_timeout=7000
rng_seedlist=[1,3,5,7,9] # optional, list of seeds to be used with rng, if used then in the fuzzer command, specify the position using RNG special string
