results_dir = "/Results/MORPHEUS" # directory for creating folder and files and save the results
fc_name="morpheus-mbedtls" # name of the fuzzing campaign, will be used for creating a folder

server_port=4008 # port for running the server
server_log_file_prefix="log_"
server_backlog = 15000
server_stop_command="STOP_SERVER_NOW"


fuzzer_fuzztime=86400 # seconds
fuzzer_out_dir_name="out_mbedtls_morpheus"# path to fuzzer output directory, will be created inside the results dir, should be a name only, not a path
fuzzer_seed_dir="/target/seeds" # should be absolute path
fuzzer_harness_timeout=2000 
fuzzer_harness_path="/target/build/mbedtls_harness" # should be absolute path
# fuzzer_dict_path = "/vagrant/PKCS_SPEC/pkcs1.dict"

# fuzzer command to run the fuzzer
fuzzer_command="/vagrant/myaflplusplusfork/afl-fuzz -t TIMEOUT -i SEEDDIR -o OUTDIR -s RNG -D -V FUZZTIME -- HARNESSPATH @@ PORT" 

rng_seedlist=[999] # optional, list of seeds to be used with rng, if used then in the fuzzer command, specify the position using RNG special string
