results_dir = "/Results/LIBFUZZER/10HR"
fuzzer_fuzztime=36000# seconds
fuzzer_harness_timeout=7000
rng_seedlist=[1,3,5,7,9] # optional, list of seeds to be used with rng, if used then in the fuzzer command, specify the position using RNG special string
fuzzer_command="HARNESSPATH SEEDDIR -detect_leaks=0 -max_len=500 -seed=RNG -timeout=TIMEOUT -rss_limit_mb=4096 -max_total_time=FUZZTIME -fork=1 -ignore_crashes=1 --PORT" 
