results_dir = "/Results/" # directory for creating folder and files and save the results
fc_name="sgfuzz-strongswan" # name of the fuzzing campaign, will be used for creating a folder

server_port=5007 # port for running the server
server_log_file_prefix="log_"
server_backlog = 15000
server_stop_command="STOP_SERVER_NOW"


fuzzer_fuzztime=1200# seconds
fuzzer_out_dir_name="out_strongswan_sgfuzz"# path to fuzzer output directory, will be created inside the results dir, should be a name only, not a path
fuzzer_seed_dir="/target/TEST" # should be absolute path
fuzzer_harness_timeout=4000
fuzzer_harness_path="/target/build/strongswan_harness" # should be absolute path
# fuzzer_dict_path = "/vagrant/PKCS_SPEC/pkcs1.dict"

# fuzzer command to run the fuzzer
fuzzer_command="HARNESSPATH SEEDDIR -detect_leaks=0 -max_len=500 -seed=RNG -timeout=TIMEOUT -rss_limit_mb=4096 -max_total_time=FUZZTIME -fork=1 -ignore_crashes=1 --PORT" 

rng_seedlist=[345] # optional, list of seeds to be used with rng, if used then in the fuzzer command, specify the position using RNG special string
